### ISSUE TITLE
Z Translation Problem

### ISSUE THREAD

**Issue by KyroChi** [KyroChi/Codename--Amalgamation#1]
Z translation is instant, needs to be smooth. Also needs a z jump down and z change up and z change down as all separate actions

**Comment by julesmps** [comment]
By `a z jump down and z change up and z change down as all separate actions` do you mean to make them into their own methods within the code? If not, could you please explain?

**Comment by KyroChi** [comment]
I just mean that if you press down on flat he needs to walk down but if there is a height difference he needs to jump down
